/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
		Employee emp = new Employee("1234", "John", "Doe", "charles@yahoo.com");
		emp.displayEmployee();
	}
}
