/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.HashMap;
import java.util.Map;

public class EmployeeMap {
	private Map <String, Employee> employeeMap;

	public EmployeeMap() {
		this.employeeMap = new HashMap<String, Employee>();
	}

	public Map<String, Employee> getEmployeeMap() {
		return this.employeeMap;
	}

	public void addEmployee(String employee_id, String first_name, String last_name, String email) {
		this.getEmployeeMap().put(employee_id , new Employee(employee_id, first_name, last_name, email));
	}

	public void removeEmployee(String empId) {
		this.getEmployeeMap().remove(empId);
	}

	public void getEmployee() {
		this.getEmployeeMap();
	}

}
