/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import java.util.Scanner;

import com.opencsv.CSVReader;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.List;

public class App {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);

        App app = new App(); 
        EmployeeMap employeeMap = new EmployeeMap();
        DisplayMenus menus = new DisplayMenus();

        boolean isValid = false;

        while(!isValid) {
            while(true) {
                menus.displayMenu();

                String information = in.nextLine();

                String first_name = "";
                String last_name = "";
                String email = "";


                if (information.equals("0")) {
                    System.out.println("You selected option 0");
                    break;
                } else if (information.equals("1")) {
                    while(true) {
                        System.out.print("First Name: ");
                        first_name = in.nextLine();

                        System.out.print("Last Name: ");
                        last_name = in.nextLine();

                        System.out.print("Email: ");
                        email = in.nextLine();

                        employeeMap.addEmployee(first_name, last_name, email);
                        
                        System.out.print("Do you want to add another employee? (Y/N): ");
                        String answer = in.nextLine();

                        if (answer.equals("Y") || answer.equals("y")) {
                            System.out.println("You selected option nnnnnnnnnnnnn");
                            employeeMap.displayEmployees();
                        } else if(answer.equals("N") || answer.equals("n")) {
                            System.out.println("You selected option 1");
                            break;
                        }
                    }

                } else if (information.equals("2")) {
                    employeeMap.displayEmployees();
                } else if (information.equals("3")) {
                    System.out.println("You selected option 3");
                } else if (information.equals("4")) {
                    System.out.println("You selected option 4");
                } else if (information.equals("5")) {
                    System.out.println("You selected option 5");
                }
            }
        }
	}
}
