/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import java.util.Scanner;

import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;

import java.io.FileWriter;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.List;

public class CsvOperations {
    /**
     * @param fileName Takes the name of the csv file as a string
     */
    public List <String[]> readCsvFile(String fileName) {
        List <String[]> records = null;
        try {
            InputStream in = getClass().getResourceAsStream(fileName);
            CSVReader reader = new CSVReader(new InputStreamReader(in));
            records = reader.readAll();
            reader.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return records;
    }

    /**
     * @param fileName Takes the name of the csv file as a string. 
     * @param records Takes an array of strings to write to the csv file as a List.
     */
    public List<String[]> writeCsvFile(String fileName, List <String[]> records) {
        try {
            CSVWriter writer = new CSVWriter(new FileWriter(fileName, true));
            writer.writeAll(records);
            writer.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return records;
    }

}
