/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

public class DisplayMenus {

    public static void displayMenu() {
        System.out.println("*******************************");
        System.out.println("*         Main Menu           *");
        System.out.println("*******************************");
        System.out.println("* 1. Display Employees.      *");
        System.out.println("* 2. Add Employee.           *");
        System.out.println("* 3. Remove Employee.        *");
        System.out.println("* 4. Update Employee.        *");
        System.out.println("* 5. View Ex-Employees(rmvd) *");
        System.out.println("*******************************");
    }
}
