/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeTest {
    @Test public void testEmployeeId() {
		Employee emp = new Employee("12", "carl", "hagen", "charles@gmail.com");
		assertEquals("12", emp.getEmployeeId());
	}

	@Test public void testFirstName() {
		Employee emp = new Employee("12", "carl", "hagen", "charles@gmail.com");
		assertEquals("carl", emp.getFirstName());
	}

	@Test public void testLastName() {
		Employee emp = new Employee("12", "carl", "hagen", "charles@gmail.com");
		assertEquals("hagen", emp.getLastName());
	}

	@Test public void testEmail() {
		Employee emp = new Employee("12", "carl", "hagen", "charles@gmail.com");
		assertEquals("charles@gmail.com", emp.getEmail());
	}
}
