/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;

public class CsvOperationsTest {
    @Test public void createCsvFile() {
        String filename = "TestEmployee.csv";

        File file = new File(filename);
        CsvOperations csvopen = new CsvOperations();
        List <Employee> employeelist = new ArrayList<>();

        if (file.exists()) {
            System.out.println("File Exists");
        } else {
            System.out.println("Path does not exist");
        }

        employeelist.add(new Employee("1", "Charles", "Barley", "tested@yeaboiiiiiii.com"));
        employeelist.add(new Employee("2", "Carls", "Junior", "charlesjunior@yoohoo.com"));
        employeelist.add(new Employee("3", "Hello", "Junior", "hijunior@fakemail.com"));

        List<String[]> employeestringlist = new ArrayList<>();

        for (Employee currentEmployee : employeelist) {
            String[] employee = {
                currentEmployee.getEmployeeId(),
                currentEmployee.getFirstName(),
                currentEmployee.getLastName(),
                currentEmployee.getEmail()
            };

            employeestringlist.add(employee);
        }
        
        csvopen.writeCsvFile(filename, employeestringlist);
        
        System.out.println(file);
        assertTrue(file.exists());
    }
}
