/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeMapTest {
    @Test public void testEmployeeMapSize() {
		EmployeeMap empMap = new EmployeeMap();

		empMap.addEmployee("1", "John", "Doe", "john.doe@example.com");
		empMap.addEmployee("2", "Jane", "Smith", "jane.smith@example.com");
		empMap.addEmployee("3", "Michael", "Johnson", "michael.johnson@example.com");
		empMap.addEmployee("4", "Emily", "Williams", "emily.williams@example.com");
		empMap.addEmployee("5", "Christopher", "Brown", "christopher.brown@example.com");
		empMap.addEmployee("6", "Amanda", "Jones", "amanda.jones@example.com");
		empMap.addEmployee("7", "David", "Garcia", "david.garcia@example.com");
		empMap.addEmployee("8", "Sarah", "Martinez", "sarah.martinez@example.com");
		empMap.addEmployee("9", "James", "Hernandez", "james.hernandez@example.com");
		empMap.addEmployee("10", "Jennifer", "Young", "jennifer.young@example.com");
		empMap.addEmployee("11", "Matthew", "King", "matthew.king@example.com");
		empMap.addEmployee("12", "Jessica", "Lee", "jessica.lee@example.com");
		empMap.addEmployee("13", "Daniel", "Walker", "daniel.walker@example.com");
		empMap.addEmployee("14", "Ashley", "Allen", "ashley.allen@example.com");
		empMap.addEmployee("15", "Robert", "Green", "robert.green@example.com");
		empMap.addEmployee("16", "Megan", "Evans", "megan.evans@example.com");
		empMap.addEmployee("17", "William", "Thomas", "william.thomas@example.com");
		empMap.addEmployee("18", "Elizabeth", "Harris", "elizabeth.harris@example.com");
		empMap.addEmployee("19", "Joseph", "Clark", "joseph.clark@example.com");
		empMap.addEmployee("20", "Nicole", "Lewis", "nicole.lewis@example.com");
		empMap.addEmployee("21", "David", "Robinson", "david.robinson@example.com");
		empMap.addEmployee("22", "Melissa", "Walker", "melissa.walker@example.com");
		empMap.addEmployee("23", "Charles", "Perez", "charles.perez@example.com");
		empMap.addEmployee("24", "Laura", "Hall", "laura.hall@example.com");
		empMap.addEmployee("25", "Kevin", "Young", "kevin.young@example.com");
		empMap.addEmployee("26", "Amanda", "Wright", "amanda.wright@example.com");
		empMap.addEmployee("27", "John", "Lopez", "john.lopez@example.com");
		empMap.addEmployee("28", "Stephanie", "Hill", "stephanie.hill@example.com");
		empMap.addEmployee("29", "Andrew", "Scott", "andrew.scott@example.com");
		empMap.addEmployee("30", "Samantha", "Green", "samantha.green@example.com");

		assertEquals(30, empMap.getEmployeeMap().size());
	}

	@Test public void testEmployeeData() {
		EmployeeMap empMap = new EmployeeMap();
		
		empMap.addEmployee("1", "John", "Doe", "john.doe@example.com");
		empMap.addEmployee("2", "Jane", "Smith", "jane.smith@example.com");
		empMap.addEmployee("3", "Michael", "Johnson", "michael.johnson@example.com");
		empMap.addEmployee("4", "Emily", "Williams", "emily.williams@example.com");

		Employee john = empMap.getEmployeeMap().get("1");
		Employee jane = empMap.getEmployeeMap().get("2");
		Employee michael = empMap.getEmployeeMap().get("3");
		Employee emily = empMap.getEmployeeMap().get("4");

		assertEquals("John", john.getFirstName());
		assertEquals("Doe", john.getLastName());
		assertEquals("john.doe@example.com", john.getEmail());

		assertEquals("Jane", jane.getFirstName());
		assertEquals("Smith", jane.getLastName());
		assertEquals("jane.smith@example.com", jane.getEmail());

		assertEquals("Michael", michael.getFirstName());
		assertEquals("Johnson", michael.getLastName());
		assertEquals("michael.johnson@example.com", michael.getEmail());

		assertEquals("Emily", emily.getFirstName());
		assertEquals("Williams", emily.getLastName());
		assertEquals("emily.williams@example.com", emily.getEmail());
	}
}
