/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeMapTest {
    @Test public void testEmployeeMapSize() {
		EmployeeMap empMap = new EmployeeMap();

		empMap.addEmployee("John", "Doe", "john.doe@example.com");
		empMap.addEmployee("Jane", "Smith", "jane.smith@example.com");
		empMap.addEmployee("Michael", "Johnson", "michael.johnson@example.com");
		empMap.addEmployee("Emily", "Williams", "emily.williams@example.com");
		empMap.addEmployee("Christopher", "Brown", "christopher.brown@example.com");
		empMap.addEmployee("Amanda", "Jones", "amanda.jones@example.com");
		empMap.addEmployee("David", "Garcia", "david.garcia@example.com");
		empMap.addEmployee("Sarah", "Martinez", "sarah.martinez@example.com");
		empMap.addEmployee("James", "Hernandez", "james.hernandez@example.com");
		empMap.addEmployee("Jennifer", "Young", "jennifer.young@example.com");
		empMap.addEmployee("Matthew", "King", "matthew.king@example.com");
		empMap.addEmployee("Jessica", "Lee", "jessica.lee@example.com");
		empMap.addEmployee("Daniel", "Walker", "daniel.walker@example.com");
		empMap.addEmployee("Ashley", "Allen", "ashley.allen@example.com");
		empMap.addEmployee("Robert", "Green", "robert.green@example.com");
		empMap.addEmployee("Megan", "Evans", "megan.evans@example.com");
		empMap.addEmployee("William", "Thomas", "william.thomas@example.com");
		empMap.addEmployee("Elizabeth", "Harris", "elizabeth.harris@example.com");
		empMap.addEmployee("Joseph", "Clark", "joseph.clark@example.com");
		empMap.addEmployee("Nicole", "Lewis", "nicole.lewis@example.com");
		empMap.addEmployee("David", "Robinson", "david.robinson@example.com");
		empMap.addEmployee("Melissa", "Walker", "melissa.walker@example.com");
		empMap.addEmployee("Charles", "Perez", "charles.perez@example.com");
		empMap.addEmployee("Laura", "Hall", "laura.hall@example.com");
		empMap.addEmployee("Kevin", "Young", "kevin.young@example.com");
		empMap.addEmployee("Amanda", "Wright", "amanda.wright@example.com");
		empMap.addEmployee("John", "Lopez", "john.lopez@example.com");
		empMap.addEmployee("Stephanie", "Hill", "stephanie.hill@example.com");
		empMap.addEmployee("Andrew", "Scott", "andrew.scott@example.com");
		empMap.addEmployee("Samantha", "Green", "samantha.green@example.com");

		assertEquals(30, empMap.getEmployeeMap().size());
	}

	@Test public void testEmployeeData() {
		EmployeeMap empMap = new EmployeeMap();
		
		empMap.addEmployee("John", "Doe", "john.doe@example.com");
		empMap.addEmployee("Jane", "Smith", "jane.smith@example.com");
		empMap.addEmployee("Michael", "Johnson", "michael.johnson@example.com");
		empMap.addEmployee("Emily", "Williams", "emily.williams@example.com");

		Employee john = empMap.getEmployeeMap().get("1");
		Employee jane = empMap.getEmployeeMap().get("2");
		Employee michael = empMap.getEmployeeMap().get("3");
		Employee emily = empMap.getEmployeeMap().get("4");

		assertEquals("John", john.getFirstName());
		assertEquals("Doe", john.getLastName());
		assertEquals("john.doe@example.com", john.getEmail());

		assertEquals("Jane", jane.getFirstName());
		assertEquals("Smith", jane.getLastName());
		assertEquals("jane.smith@example.com", jane.getEmail());

		assertEquals("Michael", michael.getFirstName());
		assertEquals("Johnson", michael.getLastName());
		assertEquals("michael.johnson@example.com", michael.getEmail());

		assertEquals("Emily", emily.getFirstName());
		assertEquals("Williams", emily.getLastName());
		assertEquals("emily.williams@example.com", emily.getEmail());
	}
}
