/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.rqueztech;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmployeeTest {
    @Test public void testEmployeeId() {
		EmployeeMap emp = new EmployeeMap();
        emp.addEmployee("Charles", "Darwin", "cdarwin@gmail.com");
	    assertTrue("1", emp.getEmployeeMap().containsKey("1"));
        emp.addEmployee("Albert", "Einstein", "aeinstein@yahoo.com");
        assertTrue("2", emp.getEmployeeMap().containsKey("2"));
    }
}
